version: "3"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
    - RABBITMQ_USERNAME=rabbit
    - RABBITMQ_PASSWORD=rabbit

  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker:latest
    links:
      - postgres
    ports:
      - "80:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod # --quiet
